config/routes.rb
Rails.application.routes.draw do
  resources :plants, only: [:create, :index, :new, :show] do
    resources :reviews, only: [:create]
    resources :purchases, only: [:create]
  end
  devise_for :users
  root to: 'plants#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews, dependent: :destroy
  has_many :purchases, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  #validates :photo, presence: true
  validates :name, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :plant
  belongs_to :user
  validates :quantity, inclusion: { in: 0..10 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :plant
  belongs_to :user
  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @plants = Plant.all
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
  end

  def show
    @plant = Plant.find(params[:id])
    @review = Review.new
    @markers = [
      {
        lat: @plant.latitude,
        lng: @plant.longitude
      }
    ]
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    if @plant.save
      redirect_to plants_path
    else
      render 'new'
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :description, :quantity, :price, :photo, :address)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def create
    @plant = Plant.find(params[:plant_id])
    @purchase = Purchase.new(purchase_params)
    @purchase.plant = @plant
    @purchase.user = current_user
    @purchase.value = plant.price * quantity
    if @purchase.save
      redirect_to plant_path(@plant)
    else
      render "plants/show"
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:quantity, :value)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @plant = Plant.find(params[:plant_id])
    @review = Review.new(review_params)
    @review.plant = @plant
    @review.user = current_user
    if @review.save
      redirect_to plant_path(@plant)
    else
      render "plants/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find Your Plants</title>
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/nicolasenne/image/upload/v1606158095/find-your-plants/icon-plant_b6j1dj.svg">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


      <%= yield %>



</html>

app/views/plants/_grid-items.html.erb
<h2 class="title">Have a look at our fine selection of plants 🌱</h2>

<div class="container">

  <div class="grid">
  <% @plants.each do |plant| %>
    <div class="grid-item">
      <div class="card">

        <%= cl_image_tag plant.photo.key, class: "card-img" if plant.photo.attached? %>

        <div class="card-content">

          <h1 class="card-head"> <%= plant.name %></h1>
          <p class="card-text"><%= plant.description %></p>
          <%= link_to "Explore", plant_path(plant), class: 'btn card-btn' %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/plants/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/nicolasenne/image/upload/v1606160617/find-your-plants/background-image_no3ofn.jpg);">
  <img class="logo-white" alt="Find Your Plants logo" src="https://res.cloudinary.com/nicolasenne/image/upload/v1606159635/find-your-plants/logo-white_cfqp0r.svg">
  <h1>More plants, less problems.</h1>
  <a href="#middle" class="btn btn-ghost">Start now!</a>
</div>
<div id="middle"></div>

<%= render 'grid-items' %>

<%= render 'shared/footer' %>

app/views/plants/new.html.erb
<div class="container-new">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2>Create a new plant</h2>

      <%= simple_form_for @plant do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :quantity %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.input :address %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container-show">
  <div class="grid-show">

    <div class="grid-item-show">
      <div class="card-show">
        <div class="card-content-show">
          <h1 class="card-head-show"> <%= @plant.name %> </h1>
          <p class="card-text-show"> <%= @plant.description %> </p>

          <%= cl_image_tag @plant.photo.key, class: "card-img-show" if @plant.photo.attached? %>
          <div class="badge-show">
            <span class="badge badge-pill badge-1">Awesome</span>
            <span class="badge badge-pill badge-2">Cool Plant</span>
            <span class="badge badge-pill badge-3">Nice Defender</span>
          </div>
          <hr class="hr-1">
          <div class="price-show-grid">
            <input class="form-control numeric integer optional" type="number" step="1" name="plant[quantity]" id="plant-quantity-show">
           <span id="price-plant"><%= @plant.price %></span>
          </div>
          <hr class="hr-2">
          <a href="#" class="card-btn-show">Where To Buy  <i class="fas fa-shopping-cart"></i></a>
        </div>
      </div>
    </div>

    <div class="grid-item-show">
      <div id="map"
        style="width: 100%; height: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

<div class="container-show">
  <div class="review-show">
    <h3>Reviews</h3>
      <% if @plant.reviews.empty? %>
        <p>Be the first to let a review</p>
      <% else %>
        <ul class="list-group">
          <% @plant.reviews.each do |review| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <span class="badge badge-primary badge-pill">
                <% counter = 0 %>
                <% 5.times do %>
                  <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                  <% counter += 1 %>
                <% end %>
              </span>
              <%= review.content %>
            </li>
          <% end %>
        </ul>
      <% end %>

     <%= render "reviews/new", plant: @plant, review: @review %>

    </div>
</div>

<%= render 'shared/footer' %>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [plant, review] do |f| %>
  <%= f.input :rating, collection: 1..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with 🌱 at Find Your Plants
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#{plants_path}", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/nicolasenne/image/upload/v1606158095/find-your-plants/icon-plant_b6j1dj.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", plants_path , class: "nav-link" %>
          </li>
          <li class="nav-item-plant">
            <%= link_to "Create Plant", new_plant_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/nicolasenne/image/upload/v1606486145/find-your-plants/zombie-profile_vt4ejw.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>